# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

services:
   - mongo

variables:
  NODE_ENV: 'test'

# Pipeline:

stages:
  - install
  - build

# Jobs:

install_dependencies:
    stage: install
    script:
      - npm install
    artifacts:
      paths:
        - node_modules/

Build_and_Test:
  stage: build
  before_script:
     - npm run clean
  script:
    - npm run compile:all
    - npm test

coverage:
    stage: build
    script:
       - npm run test:report
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
    artifacts:
       paths:
          - coverage/