file:
  - ./test/functional/api/tasksTest.js
  - ./test/functional/api/teamsTest.js
  - ./test/functional/api/tracingsTest.js
  - ./test/functional/api/usersTest.js
require: '@babel/register'
exit: true
